### ISSUE TITLE
Code Explanation for transformers_multiclass_classification.ipynb

### ISSUE THREAD

**Issue by Shuailong** [abhimishra91/transformers-tutorials#8]
Thanks for sharing the excellent tutorial! However, there are some questions regarding the classifier:

The final linear layer output of the classifier should be of shape: (batch_size, num_labels), however, I find that according to the code, the final output shape is (batch_size, seq_len), which is used to calculate the cross-entropy loss. I am quite confused.

**Comment by abhimishra91** [comment]
@Shuailong , thank you for your question. The reason for that was because i was using regression as a way to determine the correct class, rather than classification. 

I have updated the code to reflect more of the classification style network where the output is now of the shape: (batch_size, num_labels)
